beryllium: Update to latest AnyKernel3

diff --git a/AnyKernel3/META-INF/com/google/android/update-binary b/AnyKernel3/META-INF/com/google/android/update-binary
--- a/AnyKernel3/META-INF/com/google/android/update-binary
+++ b/AnyKernel3/META-INF/com/google/android/update-binary
@@ -10,6 +10,7 @@ $BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMO
 
 $BOOTMODE && DIR=/sdcard || DIR=$(dirname "$ZIPFILE");
 
+test "$ANDROID_ROOT" || ANDROID_ROOT=/system;
 test "$home" || home=/tmp/anykernel;
 
 ui_print() {
@@ -17,6 +18,11 @@ ui_print() {
     echo -e "ui_print $1\nui_print" > $OUTFD;
     shift;
   done;
+}
+ui_printfile() {
+  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
+    ui_print "$line";
+  done < $1;
 }
 show_progress() { echo "progress $1 $2" > $OUTFD; }
 file_getprop() { $bb grep "^$2=" "$1" | $bb cut -d= -f2-; }
@@ -30,7 +36,7 @@ int2ver() {
   fi;
 }
 cleanup() {
-  cd $home/..;
+  cd $(dirname $home);
   rm -rf $home;
 }
 debugging() {
@@ -42,23 +48,43 @@ debugging() {
     ;;
   esac;
 }
-is_mounted() { $bb mount | $bb grep " $1 "; }
-unmount_all() {
-  ($bb umount /system;
-  if [ -d /system_root -a ! -f /system/build.prop ]; then
-    $bb umount /system_root;
+setup_mountpoint() {
+  test -L $1 && $bb mv -f $1 ${1}_link;
+  if [ ! -d $1 ]; then
+    rm -f $1;
+    mkdir $1;
   fi;
-  $bb umount /system;
-  $bb umount /vendor;
-  $bb umount /data) 2>/dev/null;
+}
+is_mounted() { $bb mount | $bb grep -q " $1 "; }
+umount_all() {
+  ($bb umount /system;
+  $bb umount -l /system;
+  if [ -e /system_root ]; then
+    $bb umount /system_root;
+    $bb umount -l /system_root;
+  fi;
+  umount /vendor;
+  umount -l /vendor;
+  if [ "$umount_data" ]; then
+    $bb umount /data;
+    $bb umount -l /data;
+  fi) 2>/dev/null;
+}
+restore_env() {
+  test "$savedpath" && export LD_LIBRARY_PATH="$savedpath";
+  test "$savedpre" && export LD_PRELOAD="$savedpre";
+  umount_all;
+  ($bb mv -f /system_link /system;
+  $bb mv -f /system_root_link /system_root;
+  $bb umount -l /dev/random) 2>/dev/null;
 }
 abort() {
-  ui_print "$*";
+  ui_print "$@";
   debugging;
   if [ ! -f anykernel.sh -o "$(file_getprop anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
     cleanup;
   fi;
-  unmount_all;
+  restore_env;
   exit 1;
 }
 
@@ -71,6 +97,17 @@ unzip -o "$ZIPFILE";
 if [ $? != 0 -o ! "$(ls tools)" ]; then
   abort "Unzip failed. Aborting...";
 fi;
+for arch32 in x86 arm; do
+  if [ -d $home/tools/$arch32 ]; then
+    bb=$home/tools/$arch32/busybox;
+    chmod 755 $bb;
+    $bb >/dev/null 2>&1;
+    if [ $? == 0 ]; then
+      $bb mv -f $home/tools/$arch32/* $home/tools;
+      break;
+    fi;
+  fi;
+done;
 bb=$home/tools/busybox;
 chmod 755 $bb;
 $bb chmod -R 755 tools bin;
@@ -80,35 +117,47 @@ if [ $? != 0 -o -z "$(ls bin)" ]; then
 fi;
 
 if [ -f banner ]; then
-  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
-    ui_print "$line";
-  done < banner;
+  ui_printfile banner;
   ui_print " " " ";
 fi;
 
 ui_print "$(file_getprop anykernel.sh kernel.string)";
 if [ -f version ]; then
   ui_print " ";
-  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
-    ui_print "$line";
-  done < version;
+  ui_printfile version;
   ui_print " ";
 fi;
 ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " " " ";
 
-unmount_all;
-if [ ! "$(is_mounted /system)" ]; then
-  $bb mount -o ro -t auto /system;
+$BOOTMODE || $bb mount -o bind /dev/urandom /dev/random;
+umount_all;
+setup_mountpoint $ANDROID_ROOT;
+if ! is_mounted $ANDROID_ROOT; then
+  $bb mount -o ro -t auto $ANDROID_ROOT;
 fi;
-($bb mount -o ro -t auto /vendor;
-$bb mount /data) 2>/dev/null;
-if [ -f /system/system/build.prop ]; then
-  $bb umount /system;
-  ($bb umount /system;
-  mkdir /system_root) 2>/dev/null;
-  $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
+case $ANDROID_ROOT in
+  /system_root) setup_mountpoint /system;;
+  /system)
+    if [ -f /system/system/build.prop ]; then
+      setup_mountpoint /system_root;
+      $bb mount --move /system /system_root;
+      if [ $? != 0 ]; then
+        $bb umount /system;
+        $bb umount -l /system 2>/dev/null;
+        $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
+      fi;
+    fi;
+  ;;
+esac;
+if is_mounted /system_root; then
   $bb mount -o bind /system_root/system /system;
 fi;
+$bb mount -o ro -t auto /vendor 2>/dev/null;
+if ! is_mounted /data; then
+  $bb mount /data;
+  umount_data=1;
+fi;
+
 savedpath="$LD_LIBRARY_PATH";
 savedpre="$LD_PRELOAD";
 unset LD_LIBRARY_PATH;
@@ -128,34 +177,34 @@ fi;
 
 if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
   ui_print "Checking device...";
-  device="$(getprop ro.product.device)";
-  product="$(getprop ro.build.product)";
+  device=$(getprop ro.product.device);
+  product=$(getprop ro.build.product);
   for testname in $(file_getprop anykernel.sh 'device.name.*'); do
     if [ "$device" == "$testname" -o "$product" == "$testname" ]; then
-      ui_print "$testname";
+      ui_print "$testname" " ";
       match=1;
       break;
     fi;
   done;
-  ui_print " ";
   if [ ! "$match" ]; then
-    abort "Unsupported device. Aborting...";
+    abort " " "Unsupported device. Aborting...";
   fi;
 fi;
 
-supported_ver="$(file_getprop anykernel.sh supported.versions | $bb tr -d '[:space:]')";
+supported_ver=$(file_getprop anykernel.sh supported.versions | $bb tr -d '[:space:]');
 if [ "$supported_ver" ]; then
   ui_print "Checking Android version...";
-  android_ver="$(file_getprop /system/build.prop ro.build.version.release)";
-  if [ "$(echo $supported_ver | $bb grep -)" ]; then
-    lo_ver=$(echo $supported_ver | $bb cut -d- -f1);
-    hi_ver=$(echo $supported_ver | $bb cut -d- -f2);
-    if [ "$(echo -e "$(int2ver $hi_ver)\n$(int2ver $lo_ver)\n$(int2ver $android_ver)" | $bb sort -g | $bb grep -n "$(int2ver $android_ver)" | $bb grep '^2:')" ]; then
+  android_ver=$(file_getprop /system/build.prop ro.build.version.release);
+  parsed_ver=$(int2ver $android_ver);
+  if echo $supported_ver | $bb grep -q '-'; then
+    lo_ver=$(int2ver "$(echo $supported_ver | $bb cut -d- -f1)");
+    hi_ver=$(int2ver "$(echo $supported_ver | $bb cut -d- -f2)");
+    if echo -e "$hi_ver\n$lo_ver\n$parsed_ver" | $bb sort -g | $bb grep -n "$parsed_ver" | $bb grep -q '^2:'; then
       supported=1;
     fi;
   else
     for ver in $(echo $supported_ver | $bb sed 's;,; ;g'); do
-      if [ "$(int2ver $ver)" == "$(int2ver $android_ver)" ]; then
+      if [ "$(int2ver $ver)" == "$parsed_ver" ]; then
         supported=1;
         break;
       fi;
@@ -164,8 +213,29 @@ if [ "$supported_ver" ]; then
   if [ "$supported" ]; then
     ui_print "$android_ver" " ";
   else
-    ui_print " ";
-    abort "Unsupported Android version. Aborting...";
+    abort " " "Unsupported Android version. Aborting...";
+  fi;
+fi;
+
+supported_lvl=$(file_getprop anykernel.sh supported.patchlevels | $bb grep -oE '[0-9]{4}-[0-9]{2}|-');
+if [ "$supported_lvl" ]; then
+  ui_print "Checking Android security patch level...";
+  android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
+  parsed_lvl=$(echo $android_lvl | $bb grep -oE '[0-9]{4}-[0-9]{2}');
+  if echo $supported_lvl | $bb grep -q '^\-'; then
+    lo_lvl=0000-00;
+    hi_lvl=$(echo $supported_lvl | $bb awk '{ print $2 }');
+  elif echo $supported_lvl | $bb grep -q ' - '; then
+    lo_lvl=$(echo $supported_lvl | $bb awk '{ print $1 }');
+    hi_lvl=$(echo $supported_lvl | $bb awk '{ print $3 }');
+  elif echo $supported_lvl | $bb grep -q '\-$'; then
+    lo_lvl=$(echo $supported_lvl | $bb awk '{ print $1 }');
+    hi_lvl=9999-99;
+  fi;
+  if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $bb sort -g | $bb grep -n "$parsed_lvl" | $bb grep -q '^2:'; then
+    ui_print "$android_lvl" " ";
+  else
+    abort " " "Unsupported Android security patch level. Aborting...";
   fi;
 fi;
 
@@ -190,7 +260,7 @@ if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
         *) modcon=system;;
       esac;
     fi;
-    if [ "$(is_mounted $modtarget)" ]; then
+    if is_mounted $modtarget; then
       $bb mount -o rw,remount -t auto $modtarget;
     fi;
     mkdir -p $(dirname $modtarget);
@@ -200,7 +270,7 @@ if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
     if [ "$modcon" ]; then
       chcon "u:object_r:${modcon}_file:s0" $modtarget;
     fi;
-    if [ "$(is_mounted $modtarget)" ]; then
+    if is_mounted $modtarget; then
       $bb mount -o ro,remount -t auto $modtarget;
     fi;
   done;
@@ -210,7 +280,7 @@ if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
 fi;
 
 ui_print " ";
-ui_print "Adding custom thermal";
+ui_print "Adding custom thermal...";
 ui_print " ";
 $bb mount -o rw,remount -t auto /system;
 $bb cp -rLf /tmp/anykernel/patch/thermal.sh /system/bin/;
@@ -227,9 +297,6 @@ if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-test "$savedpath" && export LD_LIBRARY_PATH="$savedpath";
-test "$savedpre" && export LD_PRELOAD="$savedpre";
-
-unmount_all;
+restore_env;
 
 ui_print " " " " "Done!";
